# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='tipo',
            field=models.CharField(choices=[(1, 'Crédito'), (2, 'Débito')], max_length=7),
        ),
    ]
