# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_auto_20170707_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacoes',
            old_name='nome',
            new_name='despesa',
        ),
        migrations.RemoveField(
            model_name='transacoes',
            name='tipo',
        ),
        migrations.AddField(
            model_name='transacoes',
            name='tipo_trans',
            field=models.IntegerField(choices=[(1, 'Crédito'), (2, 'Débito')], default=1),
            preserve_default=False,
        ),
    ]
