# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_auto_20170710_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_inclusao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
