# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
