# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_delete_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodespesa',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Tipos de Depesas'},
        ),
        migrations.AlterModelOptions(
            name='transacoes',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
