# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_auto_20170711_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.TipoDespesa'),
        ),
    ]
