# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0019_auto_20170712_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodespesa',
            name='incluido_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
