# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0020_tipodespesa_incluido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodespesa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tipodespesa',
            unique_together=set([('nome', 'incluido_por')]),
        ),
    ]
