# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_auto_20170721_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
