# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_auto_20170721_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='total_repeats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
