# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_auto_20170725_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='repeat_ids',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='transacoes',
            name='total_repeats',
            field=models.IntegerField(default=0),
        ),
    ]
