# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0025_auto_20170802_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='repeated_regs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.TransacoesRepetidas'),
        ),
    ]
