# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_transacoes_repeated_regs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacoes',
            name='repeated_regs',
        ),
        migrations.AlterField(
            model_name='transacoesrepetidas',
            name='pk_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Transacoes'),
        ),
    ]
