# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0027_auto_20170802_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacoesrepetidas',
            name='pk_list',
        ),
        migrations.DeleteModel(
            name='TransacoesRepetidas',
        ),
    ]
