# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0028_auto_20170803_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='tipo_trans',
            field=models.IntegerField(choices=[[1, 'Débito'], [2, 'Crédito']]),
        ),
    ]
