# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0003_mainmenu_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
