# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0004_auto_20170711_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='navmenu',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='navmenu',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
