# Generated by Django 2.0 on 2017-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_submenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmenu',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
