# Generated by Django 2.0 on 2017-12-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20171227_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubMenu',
            new_name='DropdownMenu',
        ),
    ]
