# Generated by Django 2.0 on 2018-01-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20171227_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavByDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.CharField(max_length=20)),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label', to='frontend.NavMenu')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
