# Generated by Django 2.0 on 2018-01-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20180105_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbydate',
            name='label',
        ),
        migrations.DeleteModel(
            name='NavByDate',
        ),
    ]
