# Generated by Django 2.0 on 2018-01-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20180105_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownmenu',
            name='is_navbar',
        ),
        migrations.RemoveField(
            model_name='navmenu',
            name='is_navbar',
        ),
    ]
