# Generated by Django 2.0 on 2017-12-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
    ]
    migrations.RenameField('transactions','name','label')
