# Generated by Django 2.0 on 2017-12-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20171227_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetype',
            options={'ordering': ['label']},
        ),
        migrations.AddField(
            model_name='expensetype',
            name='label',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
