# Generated by Django 2.0 on 2017-12-28 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20171227_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_transaction', models.DateTimeField(auto_now=True)),
                ('dt_creation', models.DateTimeField(auto_now=True)),
                ('parcels', models.IntegerField(default=0)),
                ('expensetype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.ExpenseType')),
            ],
            options={
                'ordering': ['-dt_creation'],
            },
        ),
    ]
