# Generated by Django 2.0 on 2017-12-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='expensetype',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
