# Generated by Django 2.0 on 2018-01-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20180102_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
