# Generated by Django 2.0 on 2018-01-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20180102_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='dt_transaction',
            field=models.DateTimeField(),
        ),
    ]
