# Generated by Django 2.0 on 2018-01-03 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20180103_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='dt_transaction',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 3, 0, 56, 44, 946663, tzinfo=utc)),
        ),
    ]
