# Generated by Django 2.0 on 2018-01-03 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20180103_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='dt_transaction',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
