# Generated by Django 2.0 on 2018-01-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20180103_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='dt_transaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
