# Generated by Django 2.0 on 2018-01-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20180103_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='dt_transaction',
            field=models.DateTimeField(),
        ),
    ]
