# Generated by Django 2.0 on 2018-01-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20180122_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='operationtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='created_by',
        ),
    ]
