# Generated by Django 2.0 on 2018-01-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_operationtype_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationtype',
            name='created_by',
        ),
    ]
