# Generated by Django 2.0 on 2018-01-22 22:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0023_remove_operationtype_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensetype',
            unique_together={('label', 'created_by')},
        ),
    ]
