# Generated by Django 2.1.5 on 2019-02-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20180122_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='dt_transaction',
            field=models.DateTimeField(verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='estabelecimento',
            field=models.CharField(max_length=50, verbose_name='Establishment'),
        ),
    ]
