# Generated by Django 2.1.5 on 2019-02-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_auto_20190206_0117'),
        ('transactions', '0025_auto_20190206_0044'),
    ]

    operations = [
    ]
